name: "docker-build-push" 

on:
  release:
    types: ["published"]
  
jobs:
  docker:
    runs-on: "ubuntu-latest"
    
    env:
      IMAGE_NAME: lnzap/bitcoind
      BITCOIND_VERSION: "0.21.1"

    steps:
      # checkout the code (git clone with fetch-depth=1... use 0 to fetch the all references)
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # set the environment variable with the name of the release tag
      - name: Set env
        run: echo "RELEASE_TAG=$(echo ${{ github.ref }} | awk -F '/' '{print $3}')" >> $GITHUB_ENV
      
      # builds the regular image
      - name: Build image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }} \
          --build-arg BITCOIND_VERSION=${{ env.BITCOIND_VERSION }} \

      # login to dockerhub
      - name: Dockerhub login
        run: |
          docker login \
          --username ${{ secrets.DOCKER_USERNAME }} \
          --password ${{ secrets.DOCKER_PASSWORD }}
      
      # Push both images to Dockerhub
      - name: Push image to Dockerhub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}